### PR TITLE
searches for the json file

### PR DESCRIPTION
**Pull request by winstxnhdw**
reduces the need to change the ros params every time the user wants to run the script on their computer @khayliang

### CODE REVIEW

**Comment by khayliang** [comment]
Bruh dont need so complicated

U can just do this

```
  <rosparam file="$(find waypoint_system)/database/location.json" />
```

Valid issue tho

**Comment by khayliang** [comment]
Request reviewer, don't need to tag.

Also why u do other people fyp

**Comment by winstxnhdw** [comment]
no bro. look at the script. it needs the full path. ur suggested code doesnt give the full path.

**Comment by khayliang** [comment]
It does 

```$(find waypoint_system)/```

Finds the absolute path of the ROS package then it's subbed into the string, so the absolute path is loaded into ROSparams

**Pull request closed without merging**
